### ISSUE TITLE
Required Changes 

### ISSUE THREAD

**Issue by Odongo006** [yaredtekle022/yaredtekle022.github.io#2]
REQUIRED CHANGES ♻️ 

- I think it would be better if you remove the html codes on your readme.md file to make it look neat.
- I think  your website url should lead you to the website pages, please this link https://pages.github.com/
so that you can refresh your knowledge about deploying your website on github.
- In order for the code to look structurally better, I suggest you to put the link from line 90 between the line 82-84.

**Comment by yaredtekle022** [comment]
Thank you
